services:
  dialogue:
    command: --debug --host mqtt --port 12183 --site-id default --session-timeout
      30 --sound wake /usr/lib/rhasspy/share/rhasspy/etc/wav/beep_hi.wav --sound recorded
      /usr/lib/rhasspy/share/rhasspy/etc/wav/beep_lo.wav --sound error /usr/lib/rhasspy/share/rhasspy/etc/wav/beep_error.wav
    depends_on:
    - mqtt
    image: rhasspy/rhasspy-dialogue-hermes
    tty: true
  intent_recognition:
    command: --intent-graph /home/rhasspy/profiles/de/intent_graph.pickle.gz --debug
      --host mqtt --port 12183 --site-id default --replace-numbers --language de_DE
      --casing lower
    depends_on:
    - mqtt
    image: rhasspy/rhasspy-nlu-hermes
    tty: true
    volumes:
    - /home/rhasspy/profiles:/home/rhasspy/profiles
  microphone:
    command: --sample-rate 16000 --sample-width 2 --channels 1 --debug --host mqtt
      --port 12183 --site-id default --device-index 0 --udp-audio-host 127.0.0.1
    depends_on:
    - mqtt
    devices:
    - /dev/snd
    image: rhasspy/rhasspy-microphone-pyaudio-hermes
    tty: true
  mqtt:
    command: -p 12183
    entrypoint: mosquitto
    image: eclipse-mosquitto
    ports:
    - 12183:12183
    tty: true
  speakers:
    command: --play-command 'aplay -q -t wav -D plughw:CARD=Headphones,DEV=0' --list-command
      'aplay -L' --debug --host mqtt --port 12183 --site-id default
    depends_on:
    - mqtt
    devices:
    - /dev/snd
    image: rhasspy/rhasspy-speakers-cli-hermes
    tty: true
  speech_to_text:
    command: --acoustic-model /home/rhasspy/profiles/de/acoustic_model --dictionary
      /home/rhasspy/profiles/de/dictionary.txt --language-model /home/rhasspy/profiles/de/language_model.txt
      --debug --host mqtt --port 12183 --site-id default --intent-graph /home/rhasspy/profiles/de/intent_graph.pickle.gz
      --base-dictionary /home/rhasspy/profiles/de/base_dictionary.txt --base-dictionary
      /home/rhasspy/profiles/de/custom_words.txt --dictionary-casing lower --g2p-model
      /home/rhasspy/profiles/de/g2p.fst --unknown-words /home/rhasspy/profiles/de/unknown_words.txt
      --base-language-model-fst /home/rhasspy/profiles/de/base_language_model.fst
      --base-language-model-weight 0 --mixed-language-model-fst /home/rhasspy/profiles/de/mixed.fst
      --voice-skip-seconds 0 --voice-min-seconds 1 --voice-speech-seconds 0.3 --voice-silence-seconds
      0.5 --voice-before-seconds 0.5 --voice-sensitivity 1
    depends_on:
    - mqtt
    image: rhasspy/rhasspy-asr-pocketsphinx-hermes
    tty: true
    volumes:
    - /home/rhasspy/profiles:/home/rhasspy/profiles
  text_to_speech:
    command: --tts-command 'nanotts -v {lang} -o {file}' --temporary-wav --text-on-stdin
      --debug --host mqtt --port 12183 --site-id default --language de-DE
    depends_on:
    - mqtt
    image: rhasspy/rhasspy-tts-cli-hermes
    tty: true
  wake:
    command: --keyphrase 'hey apollo' --keyphrase-threshold 1e-30 --acoustic-model
      /home/rhasspy/profiles/de/acoustic_model --dictionary /home/rhasspy/profiles/de/base_dictionary.txt
      --dictionary /home/rhasspy/profiles/de/dictionary.txt --dictionary /home/rhasspy/profiles/de/custom_words.txt
      --debug --host mqtt --port 12183 --site-id default
    depends_on:
    - mqtt
    image: rhasspy/rhasspy-wake-pocketsphinx-hermes
    tty: true
    volumes:
    - /home/rhasspy/profiles:/home/rhasspy/profiles
version: '2'
